# Generated by Django 4.2.14 on 2024-08-05 20:54

from django.db import migrations, models
import sintonar.apps.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphoto",
            name="photos",
            field=models.ImageField(
                upload_to=sintonar.apps.authentication.models.model_directory_path
            ),
        ),
    ]
