# Generated by Django 4.1.3 on 2023-02-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_uploaded_photo',
            field=models.BooleanField(default=False),
        ),
    ]
